from tkinter import *
root=Tk()
frame=Frame(root)
frame.pack()
bottomframe= Frame(root)
bottomframe.pack(side=LEFT)
bb=Button(frame,text= "Blue",fg= "Blue")
bb.pack(side= LEFT)
blb=Button(frame,text= "Black",fg= "black")
blb.pack(side= RIGHT)
rb=Button(frame,text= "Red",fg= "Red")
rb.pack(side= BOTTOM)
bb=Button(frame,text= "Indigo",fg= "Indigo")
bb.pack(side= TOP)
root.mainloop()
