from tkinter import *
root=Tk()
frame=Frame(root)
frame.pack()
bottomframe= Frame(root)
bottomframe.pack(side=LEFT)
bb=Button(frame,text= "Blue",fg= "Blue")
bb.pack(side= LEFT)
brb=Button(frame,text= "Black",fg= "black")
brb.pack(side= LEFT)
rb=Button(frame,text= "Red",fg= "Red")
rb.pack(side= RIGHT)
bb1=Button(bottomframe,text= "Indigo",fg= "Indigo")
bb1.pack(side= BOTTOM)
root.mainloop()
