from tkinter import Toplevel, Button, Tk, Menu
top= Tk()
menubar= Menu(top)
file= Menu(menubar,tearoff=0)
file.add_command(label="New")
file.add_command(label="Open")
file.add_command(label="Save")
file.add_command(label="Save As")
file.add_separator()
file.add_command(label="Page setup")
file.add_command(label="Print")
file.add_separator()
file.add_command(label="Exit",command= top.quit)
menubar.add_cascade(label="File",menu= file)

Edit=Menu(menubar,tearoff=0)
Edit.add_command(label='undo')
Edit.add_separator()
Edit.add_command(label='Cut')
Edit.add_command(label='Copy')
Edit.add_command(label='Paste')
Edit.add_command(label='Delete')
Edit.add_command(label='Select all')
menubar.add_cascade(label="Edit",menu=Edit)

Insert=Menu(menubar,tearoff=0)
Insert.add_command(label='Cover page')
Insert.add_command(label='Blank page')
Insert.add_command(label='Break page')
Insert.add_separator()
Insert.add_command(label='Table')
Insert.add_separator()
Insert.add_command(label='Shapes')
Insert.add_command(label='Chart')
Insert.add_separator()
Insert.add_command(label='Header')
Insert.add_command(label='Footer')
menubar.add_cascade(label="Insert",menu=Insert)

Format=Menu(menubar,tearoff=0)
Format.add_command(label='Calibri')
Format.add_command(label='Font')
Format.add_command(label='Page color')
Format.add_command(label='Page border')
menubar.add_cascade(label="Format",menu=Format)

Help=Menu(menubar,tearoff=0)
Help.add_command(label='About')
menubar.add_cascade(label="Help",menu=Help)
top.config(menu=menubar)
top.mainloop()

