# -*- coding: utf-8 -*-
"""Access Data with Coinbase Pro API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BXf3IeFWx2CXe6kF4Rtob2g7dpdb5pZn

https://colab.research.google.com/
"""

!pip install cbpro

import cbpro

print(cbpro)

public_client = cbpro.PublicClient()

print(public_client)

public_client.get_products()

public_client.get_product_ticker(product_id="BTC-USD")

historic_data = public_client.get_product_historic_rates("BTC-USD")

historic_data

import pandas

coin_columns = ["Date", "Open", "High", "Low", "Close"]

for row in historic_data:

  del row[5:]

dataframe = pandas.DataFrame(historic_data,
                 columns = coin_columns)

print(dataframe)

dataframe.describe()

print(dataframe.head())

dataframe["5-Day Moving Average"] = dataframe.Close.rolling(5).mean()

print(dataframe)

!pip install bta-lib

import btalib

simple_moving_average = btalib.sma(dataframe.Close)

print(simple_moving_average.df)

dataframe["Simple Moving Average"] = btalib.sma(dataframe.Close, period=10).df

print(dataframe)